export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_START = "GET_TRANSACTIONS_START";
export const GET_TRANSACTIONS_SUCCEED = "GET_TRANSACTIONS_SUCCEED";
export const GET_TRANSACTIONS_FAILED = "GET_TRANSACTIONS_FAILED";

export const CLEAR_STATE = "CLEAR_STATE";
